version: '3'
services:
  server:
    image: bs32g1038/meteor-reading-server:v1
    volumes:
      - ../data/meteor-reading/statics:/code/statics
      - ../data/meteor-reading/logs/server:/code/logs
    depends_on:
      - db
      - redis
    environment:
      LOG_LEVEL: error
      APP_MODULE: app.main:app
      REDIS: redis://redis
      DB: postgresql://postgres:123456@db/read_dev
  webapp:
    image: bs32g1038/meteor-reading-webapp:v1
    command: npm run start
    depends_on:
      - server
    volumes:
      - ../data/meteor-reading/crawler-images:/code/public/crawler-images
  crawler:
    image: bs32g1038/meteor-reading-crawler:v1
    volumes:
      - ../data/meteor-reading/crawler-images:/code/images
      - ../data/meteor-reading/logs/crawler:/code/src/logs
    command: npm run start
    depends_on:
      - db
      - redis
    environment:
      REDIS_HOST: redis
      DB_HOST: db
    tty: true
  nginx:
    image: bs32g1038/meteor-reading-nginx:v1
    depends_on:
      - server
      - webapp
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../data/meteor-reading/logs/nginx:/var/log/nginx
  db:
    image: postgres:11.2-alpine
    restart: always
    volumes:
      - ../data/meteor-reading/pg-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: read_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
  redis:
    image: redis:5.0.5-alpine3.9
    command: redis-server --appendonly yes
    volumes:
      - ../data/meteor-reading/redis:/data
    ports:
      - 6379:6379
