version: '3'
services:
  webapp:
    build: ./webapp
    command: npm run start
    depends_on:
      - server
    volumes:
      - ../data/meteor-reading/crawler-images:/public/crawler-images
  crawler:
    build: ./crawler
    volumes:
      - ../data/meteor-reading/crawler-images:/code/images
      - ../data/meteor-reading/logs/crawler:/code/logs
    command: npm run start
    depends_on:
      - db
      - redis
    network_mode: "host"
    tty: true
  nginx:
    build: ./nginx
    depends_on:
      - server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../data/meteor-reading/logs/nginx:/var/log/nginx
  db:
    volumes:
      - ../data/meteor-reading/pg-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    image: postgres:11.2-alpine
    restart: always
    environment:
      POSTGRES_DB: read_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
  redis:
    image: redis:5.0.5-alpine3.9
    command: redis-server --appendonly yes
    volumes:
      - ../data/meteor-reading/redis:/data
    ports:
      - 6379:6379
