version: '3'
services:
  webapp:
    image: bs32g1038/meteor-reading-webapp:v1
    command: npm run start
    depends_on:
      - server
  server:
    image: bs32g1038/meteor-reading-server:v1
    volumes:
      - ../data/meteor-reading/logs/crawler:/code/src/logs
    command: npm run start
    depends_on:
      - db
      - redis
    environment:
      REDIS_HOST: redis
      DB_HOST: db
    tty: true
  db:
    image: postgres:11.2-alpine
    restart: always
    volumes:
      - ../data/meteor-reading/pg-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: read_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
  redis:
    image: redis:5.0.5-alpine3.9
    command: redis-server --appendonly yes
    volumes:
      - ../data/meteor-reading/redis:/data
    ports:
      - 6379:6379
    sysctls:
      net.core.somaxconn: '1024'
